/hs1/lslidar_driver_node:
  ros__parameters:
    device_ip: 192.168.1.200
    lidar_type: hs1                 # 雷达类型
    msop_port: 2368
    difop_port: 2369
    pcl_type: false
    add_multicast: false
    group_ip: 224.1.1.2
    frame_id: laser_link
    min_range: 0.15
    max_range: 1000.0
    packet_rate: 450.0
    angle_disable_min: 0.0
    angle_disable_max: 0.0
    topic_name: lslidar_point_cloud
    horizontal_angle_resolution: 0.09     #40Hz:0.09  80Hz:0.18 120Hz: 0.36
    use_time_service: false              #是否使用GPS/ntp授时
    echo_num: 0                          #仅双回波模式下有效，0表示发布所有点云，1表示发布第一次回波点云，2表示发布第二次回波点云
    publish_scan: true

    #pcap: /home/ls/data/xxx.pcap                  #pcap包路径，加载pcap包时打开此注释
