/ls1550/lslidar_ls_driver_node:
  ros__parameters:
    device_ip: 192.168.1.200    #雷达ip
    msop_port: 2368             #雷达目的数据端口
    difop_port: 2369            #雷达目的设备端口
    frame_id: laser_link        #雷达点云帧id
    add_multicast: false        #是否开启组播
    group_ip: 224.1.1.2         #组播ip
    time_synchronization: false #是否使用授时
    min_range: 0.3              #点云最小距离裁剪
    max_range: 500.0            #点云最大距离裁剪
    scan_start_angle: -60       # 起始角度，范围[-60,60]
    scan_end_angle: 60          # 结束角度，范围[-60,60]
    topic_name: lslidar_point_cloud #点云话题
    packet_loss: false          #是否开启丢包检测
    packet_rate: 10000.0        #pcap包每秒包数
    #pcap: /home/ls/xxx.pcap    #pcap包路径，加载pcap包时打开此注释
